### ISSUE TITLE
How to generate .expect file?

### ISSUE THREAD

**Issue by dzwduan** [comparch-security/FlexiCAS#160]
I see that there are many .expect files for comparison under regression. How can I ensure that the .expect files are correct?

**Comment by wsong83** [comment]
The expect traces are for the purpose of debug rather than verification. If there is a way to verify a design and generate a must-be correct trace, the regression can directly use the verification rather than relying on a trace.

The underlying idea is, the expect trace is a seemly correct trace. Each commit to the master should keep the existing cache functions untouched; therefore, the produced trace should be identical with the expected one. If there is difference in the trace, either the new commit breaks existing functions (we need to fix the commit) or a bug is found regarding to existing functions (we need a bugfix). Either way, the regression tries to safeguard the existing functions.

As for the absolute correctness, if an expected trace survives a long history of commits (some are deep refactoring of the whole cache system), it is more or less correct or nearly correct. (or practically as correct as possible)

**Comment by dzwduan** [comment]
Thanks
